apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  minReadySeconds: 45  # when a new deployment applied, it waits pod ready+45seconds for application up!
  selector:
    matchLabels:
      app: demo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:   #pod template
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - image: gcr.io/sandbox-236618/demo:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent  #IfNotPresent, Always
          name: demo
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:    #selects Pods
    app: demo-app
  name: demo-app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30207
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo-app
  sessionAffinity: None   #None, ClientIP
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demo-app
  targetCPUUtilizationPercentage: 70

